import type { Claim, Report } from '../types';

export const SEED_REPORTS: Report[] = [
  {
    id: 'R-1001',
    type: 'DITEMUKAN',
    reporterName: 'Aisyah Putri',
    reporterContact: '0812xxxxxxx',
    category: 'Dompet',
    itemName: 'Dompet Kulit Hitam',
    description: 'Dompet kulit warna hitam, ada beberapa kartu di dalamnya dan sedikit uang tunai.',
    distinctiveFeatures: 'Ada goresan kecil di sisi kanan, kancing magnet.',
    color: 'Hitam',
    photoUrl: '',
    location: 'Gedung B',
    detailLocation: 'Depan ruang 204',
    date: '2026-08-12',
    time: '13:20',
    condition: 'BAIK',
    storage: 'SEKRETARIAT_HIMA',
    status: 'DITEMUKAN',
    createdAt: '2026-08-12T13:35:00.000Z',
  },
  {
    id: 'R-1002',
    type: 'HILANG',
    reporterName: 'Bagas Wirawan',
    reporterContact: '0813xxxxxxx',
    category: 'Dompet',
    itemName: 'Dompet Hitam Polos',
    description: 'Hilang saat di kantin, dompet warna hitam berisi KTM dan uang tunai.',
    distinctiveFeatures: 'Ada stiker kecil logo band di bagian dalam.',
    color: 'Hitam',
    photoUrl: '',
    location: 'Kantin',
    detailLocation: 'Meja dekat pintu keluar',
    date: '2026-08-12',
    time: '12:45',
    condition: 'BAIK',
    status: 'MENUNGGU',
    createdAt: '2026-08-12T14:02:00.000Z',
  },
  {
    id: 'R-1003',
    type: 'DITEMUKAN',
    reporterName: 'Reza Maulana',
    reporterContact: '0814xxxxxxx',
    category: 'Elektronik',
    itemName: 'Earphone Wireless Putih',
    description: 'Ditemukan tergeletak di meja laboratorium komputer.',
    distinctiveFeatures: 'Case sedikit tergores di bagian tutup.',
    color: 'Putih',
    photoUrl: '',
    location: 'Laboratorium',
    detailLocation: 'Lab Komputer 2',
    date: '2026-08-11',
    time: '16:10',
    condition: 'BAIK',
    storage: 'RUANG_DOSEN',
    status: 'DITEMUKAN',
    createdAt: '2026-08-11T16:30:00.000Z',
  },
  {
    id: 'R-1004',
    type: 'HILANG',
    reporterName: 'Citra Ayu',
    reporterContact: '0815xxxxxxx',
    category: 'Kartu / Identitas',
    itemName: 'KTM Fakultas Teknik',
    description: 'Kartu tanda mahasiswa hilang, kemungkinan jatuh di perpustakaan.',
    distinctiveFeatures: 'Ada lanyard biru terpasang di kartu.',
    color: 'Biru',
    photoUrl: '',
    location: 'Perpustakaan',
    detailLocation: 'Lantai 2, dekat rak jurnal',
    date: '2026-08-10',
    time: '10:00',
    condition: 'BAIK',
    status: 'DIVERIFIKASI',
    createdAt: '2026-08-10T10:20:00.000Z',
  },
  {
    id: 'R-1005',
    type: 'DITEMUKAN',
    reporterName: 'Dimas Prakoso',
    reporterContact: '0816xxxxxxx',
    category: 'Kunci',
    itemName: 'Kunci Motor + Gantungan',
    description: 'Ditemukan di lapangan setelah acara olahraga sore.',
    distinctiveFeatures: 'Gantungan kunci berbentuk bola sepak.',
    color: 'Silver',
    photoUrl: '',
    location: 'Lapangan',
    detailLocation: 'Dekat tribun kecil',
    date: '2026-08-09',
    time: '17:40',
    condition: 'BAIK',
    storage: 'PRIBADI',
    status: 'SUDAH_KEMBALI',
    createdAt: '2026-08-09T18:00:00.000Z',
  },
  {
    id: 'R-1006',
    type: 'HILANG',
    reporterName: 'Elang Saputra',
    reporterContact: '0817xxxxxxx',
    category: 'Elektronik',
    itemName: 'Earphone Bluetooth Putih',
    description: 'Tertinggal di lab komputer saat praktikum.',
    distinctiveFeatures: 'Case ada goresan tipis di tutupnya.',
    color: 'Putih',
    photoUrl: '',
    location: 'Laboratorium',
    detailLocation: 'Lab Komputer 2',
    date: '2026-08-12',
    time: '09:15',
    condition: 'BAIK',
    status: 'MENUNGGU',
    createdAt: '2026-08-12T09:40:00.000Z',
  },
  {
    id: 'R-1007',
    type: 'DITEMUKAN',
    reporterName: 'Farah Nabila',
    reporterContact: '0818xxxxxxx',
    category: 'Buku & Alat Tulis',
    itemName: 'Buku Catatan Bersampul Cokelat',
    description: 'Ditemukan di masjid kampus setelah salat Zuhur.',
    distinctiveFeatures: "Ada nama 'Guntur' ditulis tangan di halaman depan.",
    color: 'Cokelat',
    photoUrl: '',
    location: 'Masjid',
    detailLocation: 'Rak sandal dekat pintu masuk',
    date: '2026-08-13',
    time: '12:30',
    condition: 'BAIK',
    storage: 'OB',
    status: 'DITEMUKAN',
    createdAt: '2026-08-13T12:50:00.000Z',
  },
];

export const SEED_CLAIMS: Claim[] = [
  {
    id: 'C-2001',
    reportId: 'R-1001',
    claimantName: 'Bagas Wirawan',
    claimantContact: '0813xxxxxxx',
    answers: [
      {
        question: 'Sebutkan ciri khusus barang yang tidak terlihat pada foto.',
        answer: 'Di dalamnya ada KTM atas nama Bagas Wirawan dan struk parkir.',
      },
      {
        question: 'Di mana terakhir kali Anda menggunakan barang tersebut?',
        answer: 'Di kantin, sebelum membeli makan siang.',
      },
    ],
    status: 'MENUNGGU_VERIFIKASI',
    createdAt: '2026-08-13T09:00:00.000Z',
  },
];
